# Generated by Django 5.2.3 on 2025-07-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
    ]
